version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    container_name: postgres_db
    environment:
      POSTGRES_USER: user     # Set your database user
      POSTGRES_PASSWORD: password1  # Set your database password
      POSTGRES_DB: nutricat        # Set your database name
    ports:
      - "5432:5432"            # Expose PostgreSQL on port 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data   # Persist data in the database

volumes:
  postgres-data:               # Volume to persist the PostgreSQL database data

